; Technology File tsmc18
; Generated on Feb 10 22:55:22 2009
;     with @(#)$CDS: virtuoso version 6.1.3 01/16/2009 01:27 (cic612lnx) $


;********************************
; CONTROLS
;********************************
controls(
 techParams(
 ;( parameter           value             )
 ;( ----------          -----             )
  ( met3_VDD_layer 	"METAL3"        )
  ( maskGrid       	0.005 )
  ( cadGrid        	0.005 )
  ( drcGrid        	0.005 )
  ( mfgGrid        	0.005 )
  ( scale          	1.0 )
  ( met3_VSS_layer 	"METAL3"        )
  ( metal3_layer   	"METAL3"        )
  ( via2_layer     	"VIA23"         )
  ( met2_VDD_layer 	"METAL2"        )
  ( met2_VSS_layer 	"METAL2"        )
  ( metal2_layer   	"METAL2"        )
  ( via1_layer     	"VIA12"         )
  ( met1_VDD_layer 	"METAL1"        )
  ( met1_VSS_layer 	"METAL1"        )
  ( metal1_layer   	"METAL1"        )
  ( active_layer   	"DIFF"          )
  ( ndiff_layer    	"NDIFF"         )
  ( pdiff_layer    	"PDIFF"         )
  ( nplus_layer    	"NIMP"          )
  ( pplus_layer    	"PIMP"          )
  ( nwell_layer    	"NWELL"         )
  ( pwell_layer    	"NOTUSED"       )
  ( ipoly_layer    	"POLY1"         )
  ( ngate_layer    	"POLY1"         )
  ( pgate_layer    	"POLY1"         )
  ( contact_layer  	"CONT"          )
  ( ncon_layer     	"CONT"          )
  ( pcon_layer     	"CONT"          )
  ( bondpad_layer  	"NOTUSED"       )
  ( nstrap_layer   	"NDIFF"         )
  ( pstrap_layer   	"PDIFF"         )
  ( text_layers    	(("text" "drawing"))	 )
  ( equiv_layers   	nil	 )
  ( pinNetTextLayer	("text" "drawing")	 )
  ( turbo_purposes 	("drawing" "pin")	 )
  ( reference_lib  	"tsmc18"        )
  ( leTb_min_finger_n	2.0 )
  ( leTb_max_finger_n	50.0 )
  ( leTb_min_finger_p	2.0 )
  ( leTb_max_finger_p	50.0 )
  ( leTb_max_ngate_width	100.0 )
  ( leTb_max_ngate_length	100.0 )
  ( leTb_max_pgate_width	100.0 )
  ( leTb_max_pgate_length	100.0 )
  ( leTb_nwell_tie_offset	0.12 )
  ( leTb_pwell_tie_offset	0.0 )
  ( leTb_nplus_tie_offset	0.0 )
  ( leTb_pplus_tie_offset	0.0 )
  ( leTb_ntie_to_ptie	1.04 )
  ( leTb_nwell_tie_overlap_diff	0.0 )
  ( leTb_pwell_tie_overlap_diff	0.0 )
  ( leTb_nplus_tie_overlap_diff	0.18 )
  ( leTb_pplus_tie_overlap_diff	0.18 )
  ( leTb_ndiff_to_nwell_tie	0.0 )
  ( leTb_ndiff_to_pwell_tie	0.0 )
  ( leTb_ndiff_tie_overlap_contact	0.1 )
  ( leTb_pdiff_tie_overlap_contact	0.1 )
  ( leTb_nwell_notch	1.4 )
  ( leTb_pwell_notch	0.0 )
  ( leTb_nplus_notch	0.0 )
  ( leTb_pplus_notch	0.0 )
  ( leTb_imp_overlap_strap	0.0 )
  ( leTb_via_to_contact	0.0 )
  ( leTb_cut_type  	2               )
  ( leTb_strap_option	0               )
  ( leTb_pn_separation	1.0 )
  ( leTb_gate_overhang	0.0 )
  ( metal1_overlap_via1_eol	0.01 )
  ( metal1_overlap_via1_eol_edge	0.005 )
  ( metal2_overlap_via1_eol	0.01 )
  ( metal2_overlap_via1_eol_edge	0.005 )
  ( metal2_overlap_via2_eol	0.01 )
  ( metal2_overlap_via2_eol_edge	0.005 )
  ( metal3_overlap_via2_eol	0.09 )
  ( metal3_overlap_via2_eol_edge	0.005 )
  ( metal3_overlap_via3_eol	0.0 )
  ( metal3_overlap_via3_eol_edge	0.005 )
  ( metal4_overlap_via3_eol	0.0 )
  ( metal4_overlap_via3_eol_edge	0.005 )
  ( metal4_overlap_via4_eol	0.0 )
  ( metal4_overlap_via4_eol_edge	0.005 )
  ( metal5_overlap_via4_eol	0.0 )
  ( metal5_overlap_via4_eol_edge	0.005 )
  ( metal5_overlap_via5_eol	0.0 )
  ( metal5_overlap_via5_eol_edge	0.005 )
  ( metal6_overlap_via5_eol	0.0 )
  ( metal6_overlap_via5_eol_edge	0.005 )
  ( metal6_overlap_via6_eol	0.0 )
  ( metal6_overlap_via6_eol_edge	0.005 )
  ( metal7_overlap_via6_eol	0.0 )
  ( metal7_overlap_via6_eol_edge	0.005 )
  ( metal7_overlap_via7_eol	0.0 )
  ( metal7_overlap_via7_eol_edge	0.005 )
  ( metal8_overlap_via7_eol	0.0 )
  ( metal8_overlap_via7_eol_edge	0.005 )
  ( metal8_overlap_via8_eol	0.0 )
  ( metal8_overlap_via8_eol_edge	0.005 )
  ( metal9_overlap_via8_eol	0.0 )
  ( metal9_overlap_via8_eol_edge	0.005 )
  ( metal9_overlap_via9_eol	0.0 )
  ( metal9_overlap_via9_eol_edge	0.005 )
  ( metal10_overlap_via9_eol	0.0 )
  ( metal10_overlap_via9_eol_edge	0.005 )
  ( metal10_overlap_via10_eol	0.0 )
  ( metal10_overlap_via10_eol_edge	0.005 )
  ( metal11_overlap_via10_eol	0.0 )
  ( metal11_overlap_via10_eol_edge	0.005 )
  ( metal11_overlap_via11_eol	0.0 )
  ( metal11_overlap_via11_eol_edge	0.005 )
  ( metal12_overlap_via11_eol	0.0 )
  ( metal12_overlap_via11_eol_edge	0.005 )
  ( metal12_overlap_via12_eol	0.0 )
  ( metal12_overlap_via12_eol_edge	0.005 )
  ( metal13_overlap_via12_eol	0.0 )
  ( metal13_overlap_via12_eol_edge	0.005 )
  ( metal13_overlap_via13_eol	0.0 )
  ( metal13_overlap_via13_eol_edge	0.005 )
  ( metal14_overlap_via13_eol	0.0 )
  ( metal14_overlap_via13_eol_edge	0.005 )
  ( metal14_overlap_via14_eol	0.0 )
  ( metal14_overlap_via14_eol_edge	0.005 )
  ( metal15_overlap_via14_eol	0.0 )
  ( metal15_overlap_via14_eol_edge	0.005 )
  ( metal15_overlap_via15_eol	0.0 )
  ( metal15_overlap_via15_eol_edge	0.005 )
  ( metal16_overlap_via15_eol	0.0 )
  ( metal16_overlap_via15_eol_edge	0.005 )
  ( metal1_overlap_contact_eol	0.005 )
  ( metal1_overlap_contact_eol_edge	0.04 )
  ( ndiff_overlap_contact_eol	0.005 )
  ( ndiff_overlap_contact_eol_edge	0.04 )
  ( pdiff_overlap_contact_eol	0.1 )
  ( pdiff_overlap_contact_eol_edge	0.04 )
  ( active_overlap_contact_eol	0.1 )
  ( active_overlap_contact_eol_edge	0.04 )
  ( ipoly_overlap_contact_eol	0.1 )
  ( ipoly_overlap_contact_eol_edge	0.04 )
 ) ;techParams

 viewTypeUnits(
 ;( viewType            userUnit       dbuperuu           )
 ;( --------            --------       --------           )
 ) ;viewTypeUnits

 mfgGridResolution(
      ( 0.005000 )
 ) ;mfgGridResolution

 refTechLibs(
; techLibName            
; -----------            
 ) ;refTechLibs

 processFamily(
 ) ;processFamily

 distanceMeasure(
 ) ;distanceMeasure

) ;controls


;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(

 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:
  ( NW                        60         nwl          )
  ( NWDNW                     61         dnw          )
  ( PWDNW                     62         twl          )
  ( NTN                       63                      )
  ( NWSTI                     64                      )
  ( SBDDMY                    65         SBDDMY       )
  ( NPS2                      66         NPS2         )
  ( FLD                       67         FLD          )
  ( BSP                       68         BSP          )
  ( BSD                       69         BSD          )
  ( BSL                       70         BSL          )
  ( PDD                       71         PDD          )
  ( DMYLD                     72         DMYLD        )
  ( LDPW                      73         LDPW         )
  ( NDD                       74         NDD          )
  ( dummyf                    75         dummyf       )
  ( SEL                       76         SEL          )
  ( CF3D                      77         CF3D         )
  ( DPW                       78         DPW          )
  ( LLNW                      79         LLNW         )
  ( ODLL                      80         ODLL         )
  ( SH_P                      81         SH_P         )
  ( SH_N                      82         SH_N         )
  ( SH_PO                     83         SH_PO        )
  ( HVIO                      84         HVIO         )
  ( OW                        85         OW           )
  ( lvs                       86                      )
  ( MP                        87                      )
  ( CELL_TX2                  88                      )
  ( CAP_IMP                   89                      )
  ( CELL_RS                   90                      )
  ( CELL_TX                   91                      )
  ( BGN                       92                      )
  ( BGP                       93                      )
  ( E_ML                      94                      )
  ( YM                        95                      )
  ( CM                        96                      )
  ( MM                        97                      )
  ( MS                        98                      )
  ( LS                        99                      )
  ( CELLMV                    100                     )
  ( CELLH                     101                     )
  ( NPS                       102                     )
  ( PL                        103                     )
  ( GM                        104                     )
  ( RM                        105                     )
  ( BM                        106                     )
  ( ML                        107                     )
  ( PPS                       108                     )
  ( NMOS_VT                   109                     )
  ( CI                        110                     )
  ( CIRPO                     111                     )
  ( GM1                       112                     )
  ( GM2                       113                     )
  ( dummy7                    114        dummy7       )
  ( dummy1                    115        dummy1       )
  ( dummy2                    116        dummy2       )
  ( dummy3                    117        dummy3       )
  ( dummy4                    118        dummy4       )
  ( dummy5                    119        dummy5       )
  ( dummy6                    120        dummy6       )
  ( drain                     121        drain        )
  ( CELLD                     122                     )
  ( dummy                     127        dummy        )
 ;System-Reserved Purposes:
 ) ;techPurposes

 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( ref                       0          ref          )
  ( PWELL                     1          PWELL        )
  ( NWELL                     2          NWELL        )
  ( DIFF                      3          DIFF         )
  ( OD2                       4          OD2          )
  ( N3V                       5          N3V          )
  ( P3V                       6          P3V          )
  ( PIMP                      7          PIMP         )
  ( NIMP                      8          NIMP         )
  ( EPLY                      9          EPLY         )
  ( BPLY                      10         BPLY         )
  ( PDIFF                     11         PDIFF        )
  ( NDIFF                     12         NDIFF        )
  ( POLY1                     13         POLY1        )
  ( POLY2                     14         POLY2        )
  ( CONT                      15         CONT         )
  ( METAL1                    16         METAL1       )
  ( VIA12                     17         VIA12        )
  ( METAL2                    18         METAL2       )
  ( PAD                       19         PAD          )
  ( BPI                       20         BPI          )
  ( VIA67                     21         VIA67        )
  ( METAL7                    22         METAL7       )
  ( VTM_P                     23         VTM_P        )
  ( VTM_N                     24         VTM_N        )
  ( VTDP                      25         VTDP         )
  ( VTDN                      26         VTDN         )
  ( VIA23                     27         VIA23        )
  ( METAL3                    28         METAL3       )
  ( VIA34                     29         VIA34        )
  ( ESD                       30         ESD          )
  ( METAL4                    31         METAL4       )
  ( VIA45                     32         VIA45        )
  ( METAL5                    33         METAL5       )
  ( RPO                       34         RPO          )
  ( P2V                       35         P2V          )
  ( ESD2DUMMY                 36         ESD2DUM      )
  ( PTDIODE                   37         PTDIODE      )
  ( METAL6                    38         METAL6       )
  ( VIA56                     39         VIA56        )
  ( CTM5                      40         CTM5         )
  ( NTN                       41         NTN          )
  ( ESD3DUMMY                 42         ESD3DUM      )
  ( DRC2DUMMY                 43         DRC2DUM      )
  ( CTMDUMMY                  44         CTMDUMM      )
  ( RHDUMMY                   45         RHDUMMY      )
  ( INDDUMMY                  46         INDDUMM      )
  ( ESD1DUMMY                 47         ESD1DUM      )
  ( HRI                       48         HRI          )
  ( BJTDUMMY                  49         BJTDUMM      )
  ( PSUB2                     50         PSUB2        )
  ( HOTWL                     51         HOTWL        )
  ( RWDUMMY                   52         RWDUMMY      )
  ( VCDUMMY                   53         VCDUMMY      )
  ( RPDUMMY                   54         RPDUMMY      )
  ( EXCL                      55         EXCL         )
  ( DIODUMMY                  56         DIODUMM      )
  ( VARDUMMY                  57         VARDUMM      )
  ( SDI                       58         SDI          )
  ( TEXT                      59         TEXT         )
  ( DRCDUMMY                  60         DRCDUMM      )
  ( N2V                       61         N2V          )
  ( RLPPDUMMY                 62         RLPPDUM      )
  ( CTM2                      63         CTM2         )
  ( CTM3                      64         CTM3         )
  ( DPDUMMY                   65         DPDUMMY      )
  ( PLDUMMY                   66         PLDUMMY      )
  ( CTM4                      67         CTM4         )
  ( CDUMMY                    68         CDUMMY       )
  ( RMDUMMY                   69         RMDUMMY      )
  ( CELLIMP                   70         CELLIMP      )
  ( MICO                      71         MICO         )
  ( VICO                      72         VICO         )
  ( VIAEXCL                   73         VIAEXCL      )
  ( RODUMMY                   75         RODUMMY      )
  ( OTP                       77         OTP          )
  ( PDIMP                     78         PDIMP        )
  ( PUIMP                     79         PUIMP        )
  ( CELLBRC1                  80         CELLBRC      )
  ( BLBRC2                    81         BLBRC2       )
  ( DNW                       82         DNW          )
  ( P1W                       83         P1W          )
  ( P1R                       84         P1R          )
  ( SAC                       85         SAC          )
  ( C1                        86         C1           )
  ( C2                        87         C2           )
  ( DPITCH                    88         DPITCH       )
  ( PLMIDE                    89         PLMIDE       )
  ( LMARK                     90         LMARK        )
  ( LW                        91         LW           )
  ( PO1                       92         PO1          )
  ( HVPSW                     93         HVPSW        )
  ( FLASH                     94         FLASH        )
  ( MTPCELL                   95         MTPCELL      )
  ( FGT                       96         FGT          )
  ( HVII                      97         HVII         )
  ( HV                        98         HV           )
  ( HVNW                      99         HVNW         )
  ( HVOX                      100        HVOX         )
  ( HNVT                      101        HNVT         )
  ( "1TDMY"                   102        "1TDMY"      )
  ( WELLBODY                  103        WELLBOD      )
  ( WBDMY                     104        WBDMY        )
  ( NOOPC                     105        NOOPC        )
  ( NBL                       106        NBL          )
  ( OVERLAP                   107        OVERLAP      )
  ( HVTN                      108        HVTN         )
  ( HVTP                      109        HVTP         )
  ( RFDUMMY                   110        RFDUMMY      )
  ( IMSOR                     111        IMSOR        )
  ( SLTEXCL                   112        SLTEXCL      )
  ( IP                        113        IP           )
  ( UBM                       114        UBM          )
  ( CBD                       115        CBD          )
  ( PSUB                      116        PSUB         )
  ( MD                        117        MD           )
  ( VIAD                      118        VIAD         )
  ( PMDMY                     119        PMDMY        )
  ( FW                        120        FW           )
  ( CODEP                     121        CODEP        )
  ( MCEL                      122        MCEL         )
  ( CODEC                     123        CODEC        )
  ( DMN2V                     124        DMN2V        )
  ( DMEXCL                    125        DMEXCL       )
  ( DMP2V                     126        DMP2V        )
  ( boundary                  127        boundar      )
  ( ODBLK                     128        ODBLK        )
  ( POBLK                     129        POBLK        )
  ( PV_P                      130        PV_P         )
  ( PV_N                      131        PV_N         )
  ( BASE_N                    132        BASE_N       )
  ( ZERO_VTP                  133        ZERO_VTP     )
  ( LOGO                      134        LOGO         )
  ( PPI                       135        PPI          )
  ( MOMDMY                    136        MOMDMY       )
  ( TSV                       138        TSV          )
  ( TSV_CB                    139        TSV_CB       )
  ( TSV_PPI                   140        TSV_PPI      )
  ( SEALRING                  141        SEALRING     )
  ( ULLNW                     142        ULLNW        )
  ( ULLNLDD                   143        ULLNLDD      )
  ( HVPRDMY                   144        HVPRDMY      )
  ( LDDMY                     145        LDDMY        )
  ( CASDMY                    146        CASDMY       )
  ( CB2                       147        CB2          )
  ( RV                        148        RV           )
  ( AP                        149        AP           )
  ( PSDMY                     150        PSDMY        )
  ( LVGDMY                    151        LVGDMY       )
  ( SGDUMMY                   152        SGDUMMY      )
  ( LEVEL                     153        LEVEL        )
  ( PBL                       154        PBL          )
  ( PPLG                      155        PPLG         )
  ( NDN                       156        NDN          )
  ( NLV                       157        NLV          )
  ( BSOX                      158        BSOX         )
  ( PXBA                      159        PXBA         )
  ( NXBA                      160        NXBA         )
  ( PEMO                      161        PEMO         )
  ( PSIC                      162        PSIC         )
  ( PLV                       163        PLV          )
  ( NEM                       164        NEM          )
  ( PEM                       165        PEM          )
  ( SBDDMY                    166        SBDDMY       )
  ( LUPWDMY                   167        LUPWDMY      )
  ( SRAM                      168        SRAM         )
  ( FFCDMY                    169        FFCDMY       )
  ( SNA                       192        SNA          )
 ;System-Reserved Layers:
  ( Unrouted                  200        Unroute      )
  ( Row                       201        Row          )
  ( Group                     202        Group        )
  ( Cannotoccupy              203        noOcupy      )
  ( Canplace                  204        Canplac      )
  ( hardFence                 205        hardFnc      )
  ( softFence                 206        softFnc      )
  ( y0                        207        y0           )
  ( y1                        208        y1           )
  ( y2                        209        y2           )
  ( y3                        210        y3           )
  ( y4                        211        y4           )
  ( y5                        212        y5           )
  ( y6                        213        y6           )
  ( y7                        214        y7           )
  ( y8                        215        y8           )
  ( y9                        216        y9           )
  ( designFlow                217        dsnFlow      )
  ( stretch                   218        stretch      )
  ( edgeLayer                 219        edgeLyr      )
  ( changedLayer              220        chngLyr      )
  ( unset                     221        unset        )
  ( unknown                   222        unknown      )
  ( spike                     223        spike        )
  ( hiz                       224        hiz          )
  ( resist                    225        resist       )
  ( drive                     226        drive        )
  ( supply                    227        supply       )
  ( wire                      228        wire         )
  ( pin                       229        pin          )
  ( text                      230        text         )
  ( device                    231        device       )
  ( border                    232        border       )
  ( snap                      233        snap         )
  ( align                     234        align        )
  ( prBoundary                235        prBndry      )
  ( instance                  236        instnce      )
  ( annotate                  237        anotate      )
  ( marker                    238        marker       )
  ( select                    239        select       )
  ( substrate                 240        substra      )
  ( grid                      251        grid         )
  ( axis                      252        axis         )
  ( hilite                    253        hilite       )
  ( background                254        bkground     )
 ) ;techLayers

 techLayerPurposePriorities(
 ;layers are ordered from lowest to highest priority
 ;( LayerName                 Purpose    )
 ;( ---------                 -------    )
  ( ref                       drawing    )
  ( PWELL                     drawing    )
  ( NWELL                     drawing    )
  ( HVNW                      drawing    )
  ( PSUB                      drawing    )
  ( ULLNW                     drawing    )
  ( ULLNLDD                   drawing    )
  ( DIFF                      drawing    )
  ( DIFF                      dummy      )
  ( PDIFF                     drawing    )
  ( NDIFF                     drawing    )
  ( OD2                       drawing    )
  ( POLY1                     drawing    )
  ( POLY1                     dummy      )
  ( POLY2                     drawing    )
  ( EPLY                      drawing    )
  ( BPLY                      drawing    )
  ( N2V                       drawing    )
  ( N3V                       drawing    )
  ( P2V                       drawing    )
  ( P3V                       drawing    )
  ( PIMP                      drawing    )
  ( NIMP                      drawing    )
  ( ESD                       drawing    )
  ( RPO                       drawing    )
  ( CONT                      drawing    )
  ( CONT                      grid       )
  ( CONT                      blockage   )
  ( METAL1                    drawing    )
  ( METAL1                    grid       )
  ( METAL1                    blockage   )
  ( VIA12                     drawing    )
  ( VIA12                     grid       )
  ( VIA12                     blockage   )
  ( METAL2                    drawing    )
  ( METAL2                    grid       )
  ( METAL2                    blockage   )
  ( VIA23                     drawing    )
  ( VIA23                     grid       )
  ( VIA23                     blockage   )
  ( METAL3                    drawing    )
  ( METAL3                    grid       )
  ( METAL3                    blockage   )
  ( VIA34                     drawing    )
  ( METAL4                    drawing    )
  ( VIA45                     drawing    )
  ( METAL5                    drawing    )
  ( VIA56                     drawing    )
  ( METAL6                    drawing    )
  ( VIA67                     drawing    )
  ( METAL7                    drawing    )
  ( VICO                      drawing    )
  ( VICO                      grid       )
  ( VICO                      blockage   )
  ( MICO                      drawing    )
  ( MICO                      grid       )
  ( MICO                      blockage   )
  ( PAD                       drawing    )
  ( RV                        drawing    )
  ( AP                        drawing    )
  ( CB2                       drawing    )
  ( WBDMY                     drawing    )
  ( FW                        drawing    )
  ( OVERLAP                   drawing    )
  ( BPI                       drawing    )
  ( VTM_P                     drawing    )
  ( VTM_N                     drawing    )
  ( VTDP                      drawing    )
  ( VTDN                      drawing    )
  ( HRI                       drawing    )
  ( CTM2                      drawing    )
  ( CTM3                      drawing    )
  ( CTM4                      drawing    )
  ( CTM5                      drawing    )
  ( METAL1                    pin        )
  ( METAL2                    pin        )
  ( METAL3                    pin        )
  ( METAL4                    pin        )
  ( METAL5                    pin        )
  ( METAL6                    pin        )
  ( METAL7                    pin        )
  ( DIFF                      pin        )
  ( NWELL                     pin        )
  ( POLY1                     pin        )
  ( POLY1                     lvs        )
  ( MD                        pin        )
  ( AP                        pin        )
  ( UBM                       pin        )
  ( BJTDUMMY                  drawing    )
  ( PSUB2                     drawing    )
  ( HOTWL                     drawing    )
  ( RWDUMMY                   drawing    )
  ( RWDUMMY                   drawing1   )
  ( RPDUMMY                   drawing    )
  ( RPDUMMY                   drawing1   )
  ( RMDUMMY                   drawing    )
  ( RMDUMMY                   drawing1   )
  ( RMDUMMY                   drawing2   )
  ( RMDUMMY                   drawing3   )
  ( RMDUMMY                   drawing4   )
  ( RMDUMMY                   drawing5   )
  ( RMDUMMY                   drawing6   )
  ( MOMDMY                    drawing    )
  ( MOMDMY                    drawing1   )
  ( MOMDMY                    drawing2   )
  ( MOMDMY                    drawing3   )
  ( MOMDMY                    drawing4   )
  ( MOMDMY                    drawing5   )
  ( MOMDMY                    drawing6   )
  ( VIAEXCL                   dummy1     )
  ( VIAEXCL                   dummy2     )
  ( VIAEXCL                   dummy3     )
  ( VIAEXCL                   dummy4     )
  ( VIAEXCL                   dummy5     )
  ( VIAEXCL                   dummy6     )
  ( VIAEXCL                   dummy7     )
  ( VIAEXCL                   dummyf     )
  ( VCDUMMY                   drawing    )
  ( CDUMMY                    drawing    )
  ( DIODUMMY                  drawing    )
  ( PTDIODE                   drawing    )
  ( EXCL                      drawing    )
  ( SDI                       drawing    )
  ( TEXT                      drawing    )
  ( DRCDUMMY                  drawing    )
  ( DPDUMMY                   drawing    )
  ( PLDUMMY                   drawing    )
  ( DRC2DUMMY                 drawing    )
  ( CTMDUMMY                  drawing    )
  ( CTMDUMMY                  drawing1   )
  ( CTMDUMMY                  drawing2   )
  ( CTMDUMMY                  drawing3   )
  ( CTMDUMMY                  drawing4   )
  ( RHDUMMY                   drawing    )
  ( INDDUMMY                  drawing    )
  ( INDDUMMY                  drawing1   )
  ( RLPPDUMMY                 drawing    )
  ( HVPRDMY                   drawing    )
  ( LDDMY                     drawing    )
  ( CASDMY                    drawing    )
  ( PSDMY                     drawing    )
  ( LVGDMY                    drawing    )
  ( SBDDMY                    drawing    )
  ( SGDUMMY                   SBDDMY     )
  ( LUPWDMY                   drawing    )
  ( SRAM                      dummy1     )
  ( SRAM                      dummy2     )
  ( SRAM                      dummy3     )
  ( NOOPC                     drawing    )
  ( marker                    error      )
  ( marker                    warning    )
  ( CELLIMP                   drawing    )
  ( PV_P                      drawing    )
  ( PV_N                      drawing    )
  ( BASE_N                    drawing    )
  ( ZERO_VTP                  drawing    )
  ( LOGO                      drawing    )
  ( PPI                       drawing    )
  ( RODUMMY                   drawing    )
  ( PDIMP                     drawing    )
  ( PUIMP                     drawing    )
  ( "1TDMY"                   drawing    )
  ( CELLBRC1                  drawing    )
  ( BLBRC2                    drawing    )
  ( DNW                       drawing    )
  ( P1W                       drawing    )
  ( P1R                       drawing    )
  ( SAC                       drawing    )
  ( C1                        drawing    )
  ( C2                        drawing    )
  ( DPITCH                    drawing    )
  ( PLMIDE                    drawing    )
  ( PMDMY                     drawing    )
  ( NTN                       drawing    )
  ( HVTP                      drawing    )
  ( HVTN                      drawing    )
  ( NBL                       drawing    )
  ( HVOX                      drawing    )
  ( HVPSW                     drawing    )
  ( HV                        SH_P       )
  ( HV                        SH_N       )
  ( HV                        SH_PO      )
  ( HV                        HVIO       )
  ( HV                        OW         )
  ( HV                        DMYLD      )
  ( HV                        LDPW       )
  ( HV                        PDD        )
  ( HV                        NDD        )
  ( HV                        DPW        )
  ( prBoundary                drawing    )
  ( prBoundary                label      )
  ( prBoundary                boundary   )
  ( METAL1                    net        )
  ( METAL2                    net        )
  ( METAL3                    net        )
  ( METAL4                    net        )
  ( METAL5                    net        )
  ( METAL6                    net        )
  ( METAL7                    net        )
  ( METAL1                    boundary   )
  ( METAL2                    boundary   )
  ( METAL3                    boundary   )
  ( METAL4                    boundary   )
  ( METAL5                    boundary   )
  ( METAL6                    boundary   )
  ( METAL7                    boundary   )
  ( CONT                      net        )
  ( VIA12                     net        )
  ( VIA23                     net        )
  ( VIA34                     net        )
  ( VIA45                     net        )
  ( VIA56                     net        )
  ( VIA67                     net        )
  ( CONT                      boundary   )
  ( VIA12                     boundary   )
  ( VIA23                     boundary   )
  ( VIA34                     boundary   )
  ( VIA45                     boundary   )
  ( VIA56                     boundary   )
  ( VIA67                     boundary   )
  ( instance                  drawing    )
  ( instance                  label      )
  ( hilite                    drawing    )
  ( hilite                    drawing1   )
  ( hilite                    drawing2   )
  ( hilite                    drawing3   )
  ( hilite                    drawing4   )
  ( hilite                    drawing5   )
  ( hilite                    drawing6   )
  ( hilite                    drawing7   )
  ( hilite                    drawing8   )
  ( hilite                    drawing9   )
  ( y0                        drawing    )
  ( y1                        drawing    )
  ( y2                        drawing    )
  ( y3                        drawing    )
  ( y4                        drawing    )
  ( y5                        drawing    )
  ( y6                        drawing    )
  ( y7                        drawing    )
  ( y8                        drawing    )
  ( y9                        drawing    )
  ( grid                      drawing    )
  ( grid                      drawing1   )
  ( axis                      drawing    )
  ( border                    drawing    )
  ( align                     drawing    )
  ( device                    drawing    )
  ( device                    drawing1   )
  ( device                    drawing2   )
  ( device                    annotate   )
  ( device                    label      )
  ( wire                      drawing    )
  ( wire                      label      )
  ( wire                      flight     )
  ( select                    drawing    )
  ( drive                     drawing    )
  ( hiz                       drawing    )
  ( pin                       drawing    )
  ( pin                       annotate   )
  ( pin                       label      )
  ( resist                    drawing    )
  ( spike                     drawing    )
  ( supply                    drawing    )
  ( unknown                   drawing    )
  ( unset                     drawing    )
  ( annotate                  drawing    )
  ( designFlow                drawing    )
  ( annotate                  drawing1   )
  ( designFlow                drawing1   )
  ( annotate                  drawing2   )
  ( designFlow                drawing2   )
  ( annotate                  drawing3   )
  ( designFlow                drawing3   )
  ( annotate                  drawing4   )
  ( designFlow                drawing4   )
  ( annotate                  drawing5   )
  ( designFlow                drawing5   )
  ( annotate                  drawing6   )
  ( designFlow                drawing6   )
  ( annotate                  drawing7   )
  ( designFlow                drawing7   )
  ( annotate                  drawing8   )
  ( designFlow                drawing8   )
  ( annotate                  drawing9   )
  ( designFlow                drawing9   )
  ( edgeLayer                 drawing    )
  ( edgeLayer                 pin        )
  ( changedLayer              tool0      )
  ( changedLayer              tool1      )
  ( snap                      drawing    )
  ( stretch                   drawing    )
  ( Row                       drawing    )
  ( Row                       label      )
  ( Group                     drawing    )
  ( Group                     label      )
  ( Cannotoccupy              drawing    )
  ( Cannotoccupy              boundary   )
  ( boundary                  drawing    )
  ( Canplace                  drawing    )
  ( background                drawing    )
  ( text                      drawing    )
  ( text                      drawing1   )
  ( text                      drawing2   )
  ( Unrouted                  drawing    )
  ( Unrouted                  drawing1   )
  ( Unrouted                  drawing2   )
  ( Unrouted                  drawing3   )
  ( Unrouted                  drawing4   )
  ( Unrouted                  drawing5   )
  ( Unrouted                  drawing6   )
  ( Unrouted                  drawing7   )
  ( Unrouted                  drawing8   )
  ( Unrouted                  drawing9   )
  ( Row                       boundary   )
  ( Unrouted                  track      )
  ( marker                    annotate   )
  ( marker                    info       )
  ( marker                    ackWarn    )
  ( marker                    soError    )
  ( marker                    soCritical )
  ( marker                    critical   )
  ( marker                    fatal      )
  ( Group                     boundary   )
  ( y0                        flight     )
  ( y1                        flight     )
  ( y2                        flight     )
  ( y3                        flight     )
  ( y4                        flight     )
  ( y5                        flight     )
  ( y6                        flight     )
  ( y7                        flight     )
  ( y8                        flight     )
  ( y9                        flight     )
  ( border                    boundary   )
  ( snap                      grid       )
  ( hardFence                 drawing    )
  ( softFence                 drawing    )
  ( ESD1DUMMY                 drawing    )
  ( ESD2DUMMY                 drawing    )
  ( ESD3DUMMY                 drawing    )
  ( METAL1                    dummy      )
  ( METAL2                    dummy      )
  ( METAL3                    dummy      )
  ( METAL4                    dummy      )
  ( METAL5                    dummy      )
  ( METAL6                    dummy      )
  ( METAL7                    dummy      )
  ( MD                        dummy      )
  ( METAL1                    slot       )
  ( METAL2                    slot       )
  ( METAL3                    slot       )
  ( METAL4                    slot       )
  ( METAL5                    slot       )
  ( METAL6                    slot       )
  ( METAL7                    slot       )
  ( MD                        slot       )
  ( DIFF                      drain      )
  ( DMN2V                     drawing    )
  ( DMP2V                     drawing    )
  ( DMEXCL                    dummy1     )
  ( DMEXCL                    dummy2     )
  ( DMEXCL                    dummy3     )
  ( DMEXCL                    dummy4     )
  ( DMEXCL                    dummy5     )
  ( DMEXCL                    dummy6     )
  ( DMEXCL                    dummy7     )
  ( DMEXCL                    dummyf     )
  ( ODBLK                     dummy      )
  ( POBLK                     dummy      )
  ( SLTEXCL                   dummy1     )
  ( SLTEXCL                   dummy2     )
  ( SLTEXCL                   dummy3     )
  ( SLTEXCL                   dummy4     )
  ( SLTEXCL                   dummy5     )
  ( SLTEXCL                   dummy6     )
  ( SLTEXCL                   dummy7     )
  ( VIAD                      drawing    )
  ( VIAD                      grid       )
  ( VIAD                      blockage   )
  ( MD                        drawing    )
  ( MD                        grid       )
  ( MD                        blockage   )
  ( CBD                       drawing    )
  ( UBM                       drawing    )
  ( HNVT                      drawing    )
  ( PO1                       drawing    )
  ( FGT                       drawing    )
  ( TSV                       drawing    )
  ( TSV_CB                    drawing    )
  ( TSV_PPI                   drawing    )
  ( TSV                       pin        )
  ( TSV_PPI                   pin        )
  ( TSV                       dummy      )
  ( METAL1                    BSL        )
  ( METAL1                    BSD        )
  ( METAL1                    BSP        )
  ( RV                        BSL        )
  ( AP                        BSL        )
  ( AP                        BSP        )
  ( PAD                       BSL        )
  ( CBD                       BSL        )
  ( UBM                       BSL        )
  ( CB2                       BSL        )
  ( FFCDMY                    drawing    )
  ( IMSOR                     CELLMV     )
  ( IMSOR                     CELLH      )
  ( IMSOR                     NPS        )
  ( IMSOR                     PL         )
  ( IMSOR                     GM         )
  ( IMSOR                     RM         )
  ( IMSOR                     BM         )
  ( IMSOR                     ML         )
  ( IMSOR                     PPS        )
  ( IMSOR                     NMOS_VT    )
  ( IMSOR                     CI         )
  ( IMSOR                     CIRPO      )
  ( IMSOR                     GM1        )
  ( IMSOR                     GM2        )
  ( IMSOR                     CELLD      )
  ( IMSOR                     MS         )
  ( IMSOR                     LS         )
  ( IMSOR                     YM         )
  ( IMSOR                     CM         )
  ( IMSOR                     MM         )
  ( IMSOR                     E_ML       )
  ( IMSOR                     BGP        )
  ( IMSOR                     BGN        )
  ( IMSOR                     CELL_TX    )
  ( IMSOR                     CELL_RS    )
  ( IMSOR                     CAP_IMP    )
  ( IMSOR                     CELL_TX2   )
  ( IMSOR                     MP         )
  ( IMSOR                     DPW        )
  ( IMSOR                     CF3D       )
  ( IMSOR                     SEL        )
  ( IMSOR                     FLD        )
  ( IMSOR                     NPS2       )
  ( FLASH                     drawing    )
  ( FLASH                     LLNW       )
  ( FLASH                     ODLL       )
  ( OTP                       drawing    )
  ( HVII                      drawing    )
  ( MCEL                      drawing    )
  ( CODEP                     drawing    )
  ( CODEC                     drawing    )
  ( IP                        drawing    )
  ( RFDUMMY                   drawing    )
  ( RFDUMMY                   drawing1   )
  ( RFDUMMY                   drawing2   )
  ( LMARK                     drawing    )
  ( LW                        drawing    )
  ( SEALRING                  drawing    )
  ( VARDUMMY                  drawing    )
  ( VARDUMMY                  drawing1   )
  ( VARDUMMY                  drawing2   )
  ( VARDUMMY                  drawing3   )
  ( VARDUMMY                  drawing4   )
  ( WELLBODY                  drawing    )
  ( MTPCELL                   drawing    )
  ( LEVEL                     drawing    )
  ( PBL                       drawing    )
  ( PPLG                      drawing    )
  ( NDN                       drawing    )
  ( NLV                       drawing    )
  ( BSOX                      drawing    )
  ( PXBA                      drawing    )
  ( NXBA                      drawing    )
  ( PEMO                      drawing    )
  ( PSIC                      drawing    )
  ( PLV                       drawing    )
  ( NEM                       drawing    )
  ( PEM                       drawing    )
  ( SNA                       NTN        )
  ( SNA                       NWSTI      )
  ( SNA                       PWDNW      )
  ( SNA                       NWDNW      )
  ( SNA                       NW         )
  ( snap                      boundary   )
 ) ;techLayerPurposePriorities

 techDisplays(
 ;( LayerName    Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------    -------      ------          --- --- --------- ------- ----- )
  ( ref          drawing      redhidden_L      t t t t t )
  ( PWELL        drawing      creamshortDash_L t t t t t )
  ( NWELL        drawing      creamthickLine2_L t t t t t )
  ( HVNW         drawing      redthickLine2_L  t t t t t )
  ( PSUB         drawing      bluethickLine2_L t t t t t )
  ( ULLNW        drawing      greenthickLine_L t t t t t )
  ( ULLNLDD      drawing      orange           t t t t t )
  ( DIFF         drawing      redbackSlash_S   t t t t t )
  ( DIFF         dummy        redthickLine2_L  t t t t t )
  ( PDIFF        drawing      reddot3_S        t t t t t )
  ( NDIFF        drawing      orangedots_S     t t t t t )
  ( OD2          drawing      winColor2winColor1daggerthickLine t t t t t )
  ( POLY1        drawing      bluecrossthickLine t t t t t )
  ( POLY1        dummy        blueXthickLine   t t t t t )
  ( POLY2        drawing      pinkbrick_SN     t t t t t )
  ( EPLY         drawing      limedot4_S       t t t t t )
  ( BPLY         drawing      limedot3_S       t t t t t )
  ( N2V          drawing      grayshortDash_L  t t t t t )
  ( N3V          drawing      graythickLine2_L t t t t t )
  ( P2V          drawing      magenta          t t t t t )
  ( P3V          drawing      graythickLine_L  t t t t t )
  ( PIMP         drawing      magenta          t t t t t )
  ( NIMP         drawing      gray             t t t t t )
  ( ESD          drawing      white            t t t t t )
  ( RPO          drawing      forest           t t t t t )
  ( CONT         drawing      greencross_S     t t t t t )
  ( CONT         grid         greencross_S     t nil nil nil nil )
  ( CONT         blockage     greencross_S     t nil t t nil )
  ( METAL1       drawing      cyandot4_S       t t t t t )
  ( METAL1       grid         cyandot4_S       t nil nil nil nil )
  ( METAL1       blockage     cyandot4_S       t nil t t nil )
  ( VIA12        drawing      yellowX_S        t t t t t )
  ( VIA12        grid         yellowX_S        t nil nil nil nil )
  ( VIA12        blockage     yellowX_S        t nil t t nil )
  ( METAL2       drawing      goldstipple0_S   t t t t t )
  ( METAL2       grid         goldstipple0_S   t nil nil nil nil )
  ( METAL2       blockage     goldstipple0_S   t nil t t nil )
  ( VIA23        drawing      yellowhLine_S    t t t t t )
  ( VIA23        grid         yellowhLine_S    t nil nil nil nil )
  ( VIA23        blockage     yellowhLine_S    t nil t t nil )
  ( METAL3       drawing      forestdot4_S     t t t t t )
  ( METAL3       grid         forestdot4_S     t nil nil nil nil )
  ( METAL3       blockage     forestdot4_S     t nil t t nil )
  ( VIA34        drawing      purplevLine_S    t t t t nil )
  ( METAL4       drawing      slatedot4_S      t t t t nil )
  ( VIA45        drawing      whitetriangle_S  t t t t nil )
  ( METAL5       drawing      winColor3dot3_S  t t t t nil )
  ( VIA56        drawing      creamslash_S     t t t t nil )
  ( METAL6       drawing      tanstipple3_S    t t t t nil )
  ( VIA67        drawing      goldx_S          t t t t nil )
  ( METAL7       drawing      limedot4_S       t t t t nil )
  ( VICO         drawing      goldx_S          t t t t t )
  ( VICO         grid         goldx_S          t nil nil nil nil )
  ( VICO         blockage     goldx_S          t nil t t nil )
  ( MICO         drawing      limedot4_S       t t t t t )
  ( MICO         grid         limedot4_S       t nil nil nil nil )
  ( MICO         blockage     limedot4_S       t nil t t nil )
  ( PAD          drawing      orangedots_S     t t t t t )
  ( RV           drawing      forestx_S        t t t t t )
  ( AP           drawing      graydots_S       t t t t t )
  ( CB2          drawing      yellowdots_S     t t t t t )
  ( WBDMY        drawing      limehLine_S      t t t t t )
  ( FW           drawing      magentadots_S    t t t t t )
  ( OVERLAP      drawing      orange           t t t t t )
  ( BPI          drawing      magentathickLine2_L t t t t t )
  ( VTM_P        drawing      tanshortDash_L   t t t t t )
  ( VTM_N        drawing      tanthickLine2_L  t t t t t )
  ( VTDP         drawing      tanshortDash_L   t t t t t )
  ( VTDN         drawing      tanthickLine2_L  t t t t t )
  ( HRI          drawing      magentadot2_S    t t t t t )
  ( CTM2         drawing      purpledot1_S     t t t t t )
  ( CTM3         drawing      purpledot2_S     t t t t t )
  ( CTM4         drawing      purpledot3_S     t t t t t )
  ( CTM5         drawing      purpledot4_S     t t t t t )
  ( METAL1       pin          cyanXthickLine2  t t t nil t )
  ( METAL2       pin          goldXthickLine2  t t t nil t )
  ( METAL3       pin          forestXthickLine2 t t t nil t )
  ( METAL4       pin          slateXthickLine2 t t t nil nil )
  ( METAL5       pin          winColor3XthickLine2 t t t nil nil )
  ( METAL6       pin          tanXthickLine2   t t t nil nil )
  ( METAL7       pin          limeXthickLine2  t t t nil nil )
  ( DIFF         pin          tanXthickLine2   t t t t t )
  ( NWELL        pin          limeXthickLine2  t t t t t )
  ( POLY1        pin          blueXthickLine   t t t nil t )
  ( POLY1        lvs          tanXthickLine    t t t nil t )
  ( MD           pin          tanXthickLine2   t t t nil t )
  ( AP           pin          grayXthickLine2  t t t t t )
  ( UBM          pin          grayXthickLine2  t t t t t )
  ( BJTDUMMY     drawing      greentriangle_S  t t t t t )
  ( PSUB2        drawing      whiteX_S         t t t t t )
  ( HOTWL        drawing      orangeX_S        t t t t t )
  ( RWDUMMY      drawing      whitedaggerdashed t t t t t )
  ( RWDUMMY      drawing1     orangedaggerdashed t t t t t )
  ( RPDUMMY      drawing      winColor4brickdashDot t t t t t )
  ( RPDUMMY      drawing1     pinkbrickdashDot t t t t t )
  ( RMDUMMY      drawing      joy1brickdashDot t t t t t )
  ( RMDUMMY      drawing1     cyanbrickdashDot t t t t t )
  ( RMDUMMY      drawing2     goldbrickdashDot t t t t t )
  ( RMDUMMY      drawing3     forestbrickdashDot t t t t t )
  ( RMDUMMY      drawing4     slatebrickdashDot t t t t t )
  ( RMDUMMY      drawing5     winColor3brickdashDot t t t t t )
  ( RMDUMMY      drawing6     tanbrickdashDot  t t t t t )
  ( MOMDMY       drawing      joy1             t t t t t )
  ( MOMDMY       drawing1     red              t t t t t )
  ( MOMDMY       drawing2     purple           t t t t t )
  ( MOMDMY       drawing3     cyan             t t t t t )
  ( MOMDMY       drawing4     orange           t t t t t )
  ( MOMDMY       drawing5     lime             t t t t t )
  ( MOMDMY       drawing6     cream            t t t t t )
  ( VIAEXCL      dummy1       violet           t t t t t )
  ( VIAEXCL      dummy2       violet           t t t t t )
  ( VIAEXCL      dummy3       violet           t t t t t )
  ( VIAEXCL      dummy4       violet           t t t t t )
  ( VIAEXCL      dummy5       violet           t t t t t )
  ( VIAEXCL      dummy6       violet           t t t t t )
  ( VIAEXCL      dummy7       violet           t t t t t )
  ( VIAEXCL      dummyf       purple           t t t t t )
  ( VCDUMMY      drawing      pinkdaggerdashed t t t t t )
  ( CDUMMY       drawing      pinkdaggerdashed t t t t t )
  ( DIODUMMY     drawing      white            t t t t t )
  ( PTDIODE      drawing      white            t t t t t )
  ( EXCL         drawing      greentriangle_S  t t t t t )
  ( SDI          drawing      white            t t t t t )
  ( TEXT         drawing      white            t t t t t )
  ( DRCDUMMY     drawing      white            t t t t t )
  ( DPDUMMY      drawing      navy             t t t t t )
  ( PLDUMMY      drawing      pink             t t t t t )
  ( DRC2DUMMY    drawing      white            t t t t t )
  ( CTMDUMMY     drawing      white            t t t t t )
  ( CTMDUMMY     drawing1     purple           t t t t t )
  ( CTMDUMMY     drawing2     blue             t t t t t )
  ( CTMDUMMY     drawing3     green            t t t t t )
  ( CTMDUMMY     drawing4     orange           t t t t t )
  ( RHDUMMY      drawing      white            t t t t t )
  ( INDDUMMY     drawing      white            t t t t t )
  ( INDDUMMY     drawing1     pink             t t t t t )
  ( RLPPDUMMY    drawing      white            t t t t t )
  ( HVPRDMY      drawing      purple           t t t t t )
  ( LDDMY        drawing      orange           t t t t t )
  ( CASDMY       drawing      purple           t t t t t )
  ( PSDMY        drawing      purple           t t t t t )
  ( LVGDMY       drawing      green            t t t t t )
  ( SBDDMY       drawing      redthickLine2_L  t t t t t )
  ( SGDUMMY      SBDDMY       white            t t t t t )
  ( LUPWDMY      drawing      navy             t t t t t )
  ( SRAM         dummy1       blue             t t t t t )
  ( SRAM         dummy2       red              t t t t t )
  ( SRAM         dummy3       tan              t t t t t )
  ( NOOPC        drawing      white            t t t t t )
  ( marker       error        whiteX_SB        t t t t t )
  ( marker       warning      yellowX_SB       t t t t t )
  ( CELLIMP      drawing      green            t t t t t )
  ( PV_P         drawing      orange           t t t t t )
  ( PV_N         drawing      tan              t t t t t )
  ( BASE_N       drawing      greendashDot_L   t t t t t )
  ( ZERO_VTP     drawing      magentathickLine2_L t t t t t )
  ( LOGO         drawing      bluedashed_L     t t t t t )
  ( PPI          drawing      graydots_S       t t t t t )
  ( RODUMMY      drawing      navy             t t t t t )
  ( PDIMP        drawing      purple           t t t t t )
  ( PUIMP        drawing      gold             t t t t t )
  ( "1TDMY"      drawing      tan              t t t t t )
  ( CELLBRC1     drawing      white            t t t t nil )
  ( BLBRC2       drawing      white            t t t t nil )
  ( DNW          drawing      tan              t t t t t )
  ( P1W          drawing      greendot3_S      t t t t t )
  ( P1R          drawing      yellowdaggerthickLine2 t t t t t )
  ( SAC          drawing      white            t t t t t )
  ( C1           drawing      creamstipple0_S  t t t t t )
  ( C2           drawing      limestipple0_S   t t t t t )
  ( DPITCH       drawing      white            t t t t t )
  ( PLMIDE       drawing      white            t t t t t )
  ( PMDMY        drawing      white            t t t t t )
  ( NTN          drawing      grayshortDash_L  t t t t t )
  ( HVTP         drawing      forest           t t t t t )
  ( HVTN         drawing      magenta          t t t t t )
  ( NBL          drawing      tandot4_S        t t t t t )
  ( HVOX         drawing      golddots_S       t t t t t )
  ( HVPSW        drawing      forestdot4_S     t t t t t )
  ( HV           SH_P         golddots_S       t t t t t )
  ( HV           SH_N         magentadots_S    t t t t t )
  ( HV           SH_PO        greendots_S      t t t t t )
  ( HV           HVIO         limedot4_S       t t t t t )
  ( HV           OW           grayshortDash_L  t t t t t )
  ( HV           DMYLD        forestdot4shortDash t t t t t )
  ( HV           LDPW         cyanbrickdashDot t t t t t )
  ( HV           PDD          purpledot4_S     t t t t t )
  ( HV           NDD          limedot4_S       t t t t t )
  ( HV           DPW          grayshortDash_L  t t t t t )
  ( prBoundary   drawing      purple           t t t t t )
  ( prBoundary   label        purple           t t t t nil )
  ( prBoundary   boundary     purpledashed_L   t nil t t nil )
  ( METAL1       net          cyanX_S          t t t nil nil )
  ( METAL2       net          yellowX_S        t t t nil nil )
  ( METAL3       net          greenX_S         t t t nil nil )
  ( METAL4       net          cyanX_S          t t t nil nil )
  ( METAL5       net          whiteX_S         t t t nil nil )
  ( METAL6       net          whiteX_S         t t t nil nil )
  ( METAL7       net          whiteX_S         t t t nil nil )
  ( METAL1       boundary     cyandot4_S       t t t nil nil )
  ( METAL2       boundary     yellowdot4_S     t t t nil nil )
  ( METAL3       boundary     greendot4_S      t t t nil nil )
  ( METAL4       boundary     cyandot4_S       t t t nil nil )
  ( METAL5       boundary     whitedot4_S      t t t nil nil )
  ( METAL6       boundary     whitedot4_S      t t t nil nil )
  ( METAL7       boundary     whitedot4_S      t t t nil nil )
  ( CONT         net          limeX_S          t t t nil nil )
  ( VIA12        net          magentaX_S       t t t nil nil )
  ( VIA23        net          yellowX_S        t t t nil nil )
  ( VIA34        net          blueX_S          t t t nil nil )
  ( VIA45        net          whiteX_S         t t t nil nil )
  ( VIA56        net          whiteX_S         t t t nil nil )
  ( VIA67        net          whiteX_S         t t t nil nil )
  ( CONT         boundary     limesolid_S      t t t nil nil )
  ( VIA12        boundary     magentasolid_S   t t t nil nil )
  ( VIA23        boundary     yellowsolid_S    t t t nil nil )
  ( VIA34        boundary     bluesolid_S      t t t nil nil )
  ( VIA45        boundary     white            t t t nil nil )
  ( VIA56        boundary     white            t t t nil nil )
  ( VIA67        boundary     white            t t t nil nil )
  ( instance     drawing      red              t t t t nil )
  ( instance     label        gold             t t t t nil )
  ( hilite       drawing      white            t t t t nil )
  ( hilite       drawing1     magenta          t t t t nil )
  ( hilite       drawing2     tan              t t t t nil )
  ( hilite       drawing3     cyan             t t t t nil )
  ( hilite       drawing4     orange           t t t t nil )
  ( hilite       drawing5     lime             t t t t nil )
  ( hilite       drawing6     orange           t t t t nil )
  ( hilite       drawing7     cream            t t t t nil )
  ( hilite       drawing8     magenta          t t t t nil )
  ( hilite       drawing9     pink             t t t t nil )
  ( y0           drawing      winColor5dashed_LB t t t t nil )
  ( y1           drawing      browndashed_LB   t t t t nil )
  ( y2           drawing      reddashed_LB     t t t t nil )
  ( y3           drawing      pinkdashed_LB    t t t t nil )
  ( y4           drawing      orangedashed_LB  t t t t nil )
  ( y5           drawing      greendashed_LB   t t t t nil )
  ( y6           drawing      bluedashed_LB    t t t t nil )
  ( y7           drawing      purpledashed_LB  t t t t nil )
  ( y8           drawing      golddashed_LB    t t t t nil )
  ( y9           drawing      silverdashed_LB  t t t t nil )
  ( grid         drawing      white            t nil t nil nil )
  ( grid         drawing1     white            t nil t nil nil )
  ( axis         drawing      white            t nil t t nil )
  ( border       drawing      tan              t t t t nil )
  ( align        drawing      tan              t t t t nil )
  ( device       drawing      green            t t t t nil )
  ( device       drawing1     greensolid_S     t t t t nil )
  ( device       drawing2     greendashed_L    t t t t nil )
  ( device       annotate     yellow           t t t t nil )
  ( device       label        green            t t t t nil )
  ( wire         drawing      graysolid_S      t t t t nil )
  ( wire         label        graysolid_S      t t t t nil )
  ( wire         flight       reddashed_L      t t t t nil )
  ( select       drawing      tan              t t t t nil )
  ( drive        drawing      blue             t t t t nil )
  ( hiz          drawing      orange           t t t t nil )
  ( pin          drawing      redsolid_S       t t t t nil )
  ( pin          annotate     red              t t t t nil )
  ( pin          label        red              t t t t nil )
  ( resist       drawing      cyan             t t t t nil )
  ( spike        drawing      purple           t t t t nil )
  ( supply       drawing      lime             t t t t nil )
  ( unknown      drawing      yellow           t t t t nil )
  ( unset        drawing      forest           t t t t nil )
  ( annotate     drawing      orange           t t t t nil )
  ( designFlow   drawing      greensolid_S     t t t nil nil )
  ( annotate     drawing1     pink             t t t t nil )
  ( designFlow   drawing1     redsolid_S       t t t nil nil )
  ( annotate     drawing2     lime             t t t t nil )
  ( designFlow   drawing2     purplesolid_S    t t t nil nil )
  ( annotate     drawing3     cyan             t t t t nil )
  ( designFlow   drawing3     pinksolid_S      t t t nil nil )
  ( annotate     drawing4     yellow           t t t t nil )
  ( designFlow   drawing4     blacksolid_S     t t t nil nil )
  ( annotate     drawing5     white            t t t t nil )
  ( designFlow   drawing5     silversolid_S    t t t nil nil )
  ( annotate     drawing6     silver           t t t t nil )
  ( designFlow   drawing6     tansolid_S       t t t nil nil )
  ( annotate     drawing7     red              t t t t nil )
  ( designFlow   drawing7     cyansolid_S      t t t nil nil )
  ( annotate     drawing8     tan              t t t t nil )
  ( designFlow   drawing8     navysolid_S      t t t nil nil )
  ( annotate     drawing9     green            t t t t nil )
  ( designFlow   drawing9     orangesolid_S    t t t nil nil )
  ( edgeLayer    drawing      winColor5_B      t t t t nil )
  ( edgeLayer    pin          yellow           t t t t nil )
  ( changedLayer tool0        red              nil nil t nil nil )
  ( changedLayer tool1        yellow           nil nil t nil nil )
  ( snap         drawing      yellow           t t t t nil )
  ( stretch      drawing      yellow           t t t t nil )
  ( Row          drawing      cyan             t t t t nil )
  ( Row          label        cyan             t nil t t nil )
  ( Group        drawing      greendots_S      t t t t nil )
  ( Group        label        green            t nil t t nil )
  ( Cannotoccupy drawing      redXthickLine    t t t t nil )
  ( Cannotoccupy boundary     redthickLine_L   t t t t nil )
  ( boundary     drawing      reddashed_L      t t t t nil )
  ( Canplace     drawing      cyan             t t t t nil )
  ( background   drawing      blacksolid_S     t nil t nil nil )
  ( text         drawing      white            t t t t nil )
  ( text         drawing1     whitedashed_L    t t t t nil )
  ( text         drawing2     whitesolid_S     t t t t nil )
  ( Unrouted     drawing      winColor5dashed_L t t t t nil )
  ( Unrouted     drawing1     browndashed_L    t t t t nil )
  ( Unrouted     drawing2     reddashed_L      t t t t nil )
  ( Unrouted     drawing3     pinkdashed_L     t t t t nil )
  ( Unrouted     drawing4     orangedashed_L   t t t t nil )
  ( Unrouted     drawing5     greendashed_L    t t t t nil )
  ( Unrouted     drawing6     bluedashed_L     t t t t nil )
  ( Unrouted     drawing7     purpledashed_L   t t t t nil )
  ( Unrouted     drawing8     golddashed_L     t t t t nil )
  ( Unrouted     drawing9     silverdashed_L   t t t t nil )
  ( Row          boundary     RowBnd           t t t t nil )
  ( Unrouted     track        UnroutedTrk      t t t t nil )
  ( marker       annotate     markerAno        t t t t nil )
  ( marker       info         markerInf        t t t t nil )
  ( marker       ackWarn      markerAck        t t t t nil )
  ( marker       soError      markerSer        t t t t nil )
  ( marker       soCritical   markerScr        t t t t nil )
  ( marker       critical     markerCrt        t t t t nil )
  ( marker       fatal        markerFat        t t t t nil )
  ( Group        boundary     GroupBnd         t nil t t nil )
  ( y0           flight       y0Flt            t t t t nil )
  ( y1           flight       y1Flt            t t t t nil )
  ( y2           flight       y2Flt            t t t t nil )
  ( y3           flight       y3Flt            t t t t nil )
  ( y4           flight       y4Flt            t t t t nil )
  ( y5           flight       y5Flt            t t t t nil )
  ( y6           flight       y6Flt            t t t t nil )
  ( y7           flight       y7Flt            t t t t nil )
  ( y8           flight       y8Flt            t t t t nil )
  ( y9           flight       y9Flt            t t t t nil )
  ( border       boundary     area             t nil t t nil )
  ( snap         grid         snap             t nil t nil nil )
  ( hardFence    drawing      red              t t t t nil )
  ( softFence    drawing      yellow           t t t t nil )
  ( ESD1DUMMY    drawing      whitedot2_S      t t t t t )
  ( ESD2DUMMY    drawing      orangedot2_S     t t t t t )
  ( ESD3DUMMY    drawing      greendot2_S      t t t t t )
  ( METAL1       dummy        cyandot4thickLine2 t t t t t )
  ( METAL2       dummy        golddot4thickLine2 t t t t t )
  ( METAL3       dummy        forestdot4thickLine2 t t t t t )
  ( METAL4       dummy        slatedot4thickLine2 t t t t nil )
  ( METAL5       dummy        winColor3dot4thickLine2 t t t t nil )
  ( METAL6       dummy        tandot4thickLine2 t t t t nil )
  ( METAL7       dummy        limedot4thickLine2 t t t t nil )
  ( MD           dummy        greendot4thickLine2 t t t t t )
  ( METAL1       slot         cyandot4shortDash t t t t t )
  ( METAL2       slot         golddot4shortDash t t t t t )
  ( METAL3       slot         forestdot4shortDash t t t t t )
  ( METAL4       slot         slatedot4shortDash t t t t nil )
  ( METAL5       slot         winColor3dot4shortDash t t t t nil )
  ( METAL6       slot         tandot4shortDash t t t t nil )
  ( METAL7       slot         limedot4shortDash t t t t nil )
  ( MD           slot         orangedot4shortDash t t t t t )
  ( DIFF         drain        reddaggerdashed  t t t t t )
  ( DMN2V        drawing      white            t t t t t )
  ( DMP2V        drawing      white            t t t t t )
  ( DMEXCL       dummy1       white            t t t t t )
  ( DMEXCL       dummy2       navy             t t t t t )
  ( DMEXCL       dummy3       white            t t t t t )
  ( DMEXCL       dummy4       navy             t t t t nil )
  ( DMEXCL       dummy5       white            t t t t nil )
  ( DMEXCL       dummy6       navy             t t t t nil )
  ( DMEXCL       dummy7       white            t t t t nil )
  ( DMEXCL       dummyf       white            t t t t t )
  ( ODBLK        dummy        orange           t t t t t )
  ( POBLK        dummy        orange           t t t t t )
  ( SLTEXCL      dummy1       green            t t t t t )
  ( SLTEXCL      dummy2       orange           t t t t t )
  ( SLTEXCL      dummy3       green            t t t t t )
  ( SLTEXCL      dummy4       orange           t t t t nil )
  ( SLTEXCL      dummy5       green            t t t t nil )
  ( SLTEXCL      dummy6       orange           t t t t nil )
  ( SLTEXCL      dummy7       green            t t t t nil )
  ( VIAD         drawing      forestx_S        t t t t t )
  ( VIAD         grid         forestx_S        t nil nil nil nil )
  ( VIAD         blockage     forestx_S        t nil t t nil )
  ( MD           drawing      purple           t t t t t )
  ( MD           grid         purple           t nil nil nil nil )
  ( MD           blockage     purple           t nil t t nil )
  ( CBD          drawing      lime             t t t t t )
  ( UBM          drawing      graydot1thickLine t t t t t )
  ( HNVT         drawing      blueXthickLine   t t t t t )
  ( PO1          drawing      red              t t t t t )
  ( FGT          drawing      orange           t t t t t )
  ( TSV          drawing      reddot3thickLine t t t t t )
  ( TSV_CB       drawing      magentadot3thickLine t t t t t )
  ( TSV_PPI      drawing      orangedot2_S     t t t t t )
  ( TSV          pin          reddot3thickLine t t t t t )
  ( TSV_PPI      pin          orangedot2_S     t t t t t )
  ( TSV          dummy        greendashed_L    t t t t t )
  ( METAL1       BSL          navydot4_S       t t t t t )
  ( METAL1       BSD          navydot2thickLine2 t t t t t )
  ( METAL1       BSP          navyXthickLine2  t t t t t )
  ( RV           BSL          forestdot4_S     t t t t t )
  ( AP           BSL          graydot4_S       t t t t t )
  ( AP           BSP          grayXthickLine2  t t t t t )
  ( PAD          BSL          orangedot4_S     t t t t t )
  ( CBD          BSL          limedot4_S       t t t t t )
  ( UBM          BSL          silverdot4_S     t t t t t )
  ( CB2          BSL          yellowdot4_S     t t t t t )
  ( FFCDMY       drawing      purpleX_S        t t t t t )
  ( IMSOR        CELLMV       magenta          t t t t t )
  ( IMSOR        CELLH        orange           t t t t t )
  ( IMSOR        NPS          creamthickLine2_L t t t t t )
  ( IMSOR        PL           red              t t t t t )
  ( IMSOR        GM           red              t t t t t )
  ( IMSOR        RM           orangedots_S     t t t t t )
  ( IMSOR        BM           winColor2winColor1daggerthickLine t t t t t )
  ( IMSOR        ML           bluecrossthickLine t t t t t )
  ( IMSOR        PPS          pinkbrickdots    t t t t t )
  ( IMSOR        NMOS_VT      limedot4_S       t t t t t )
  ( IMSOR        CI           limedot3_S       t t t t t )
  ( IMSOR        CIRPO        creamdot3shortDash t t t t t )
  ( IMSOR        GM1          graydot3thickLine2 t t t t t )
  ( IMSOR        GM2          greendot3thickLine t t t t t )
  ( IMSOR        CELLD        reddot3thickLine t t t t t )
  ( IMSOR        MS           limedot3thickLine t t t t t )
  ( IMSOR        LS           reddot3thickLine t t t t t )
  ( IMSOR        YM           yellowdot3thickLine t t t t t )
  ( IMSOR        CM           cyandot3thickLine t t t t t )
  ( IMSOR        MM           magentadot3thickLine t t t t t )
  ( IMSOR        E_ML         limebrickthickLine t t t t t )
  ( IMSOR        BGP          limecrossthickLine t t t t t )
  ( IMSOR        BGN          reddot3thickLine t t t t t )
  ( IMSOR        CELL_TX      yellowdaggerthickLine t t t t t )
  ( IMSOR        CELL_RS      cyandot3thickLine t t t t t )
  ( IMSOR        CAP_IMP      magentastipple0thickLine t t t t t )
  ( IMSOR        CELL_TX2     orangestipple0_S t t t t t )
  ( IMSOR        MP           pinkstipple0_S   t t t t t )
  ( IMSOR        DPW          yellowstipple1_S t t t t t )
  ( IMSOR        CF3D         limestipple0_S   t t t t t )
  ( IMSOR        SEL          goldstipple0_S   t t t t t )
  ( IMSOR        FLD          cyanstipple0_S   t t t t t )
  ( IMSOR        NPS2         limestipple0_S   t t t t t )
  ( FLASH        drawing      lime             t t t t t )
  ( FLASH        LLNW         creamstipple0_S  t t t t t )
  ( FLASH        ODLL         orangestipple0_S t t t t t )
  ( OTP          drawing      yellowstipple1_S t t t t t )
  ( HVII         drawing      blue             t t t t t )
  ( MCEL         drawing      creamthickLine2_L t t nil t t )
  ( CODEP        drawing      magenta          t t t t t )
  ( CODEC        drawing      orange           t t t t t )
  ( IP           drawing      white            t t nil t t )
  ( RFDUMMY      drawing      white            t t nil t t )
  ( RFDUMMY      drawing1     yellow           t t nil t t )
  ( RFDUMMY      drawing2     green            t t nil t t )
  ( LMARK        drawing      whitedot2_S      t t t t t )
  ( LW           drawing      greendot2_S      t t t t t )
  ( SEALRING     drawing      gold             t t t t t )
  ( VARDUMMY     drawing      navydashed_L     t t t t t )
  ( VARDUMMY     drawing1     navydashed_L     t t t t t )
  ( VARDUMMY     drawing2     navydashed_L     t t t t t )
  ( VARDUMMY     drawing3     navydashed_L     t t t t t )
  ( VARDUMMY     drawing4     navydashed_L     t t t t t )
  ( WELLBODY     drawing      creamstipple0_S  t t nil t t )
  ( MTPCELL      drawing      goldstipple0_S   t t t t t )
  ( LEVEL        drawing      greendot3thickLine t t t t t )
  ( PBL          drawing      browndot3thickLine t t t t t )
  ( PPLG         drawing      limedot3thickLine t t t t t )
  ( NDN          drawing      reddot3thickLine t t t t t )
  ( NLV          drawing      yellowdot3thickLine t t t t t )
  ( BSOX         drawing      cyandot3thickLine t t t t t )
  ( PXBA         drawing      magentadot3thickLine t t t t t )
  ( NXBA         drawing      slatedot3thickLine t t t t t )
  ( PEMO         drawing      bluedot3thickLine t t t t t )
  ( PSIC         drawing      orangedot3thickLine t t t t t )
  ( PLV          drawing      violetdot3thickLine t t t t t )
  ( NEM          drawing      silverdot3thickLine t t t t t )
  ( PEM          drawing      purpledot3thickLine t t t t t )
  ( SNA          NTN          annotate7        t t t t t )
  ( SNA          NWSTI        annotate8        t t t t t )
  ( SNA          PWDNW        annotate6        t t t t t )
  ( SNA          NWDNW        annotate4        t t t t t )
  ( SNA          NW           annotate2        t t t t t )
  ( snap         boundary     snap             t nil t t nil )
 ) ;techDisplays

 techLayerProperties(
 ;( PropName               Layer1 [ Layer2 ]            PropValue )
 ;( --------               ------ ----------            --------- )
  ( sheetResistance        NWELL                          927.000000 )
  ( sheetResistance        PIMP                           133.000000 )
  ( sheetResistance        NIMP                           59.000000 )
  ( sheetResistance        POLY1                          311.000000 )
  ( sheetResistance        METAL1                         0.078000 )
  ( sheetResistance        METAL2                         0.078000 )
  ( sheetResistance        METAL3                         0.017800 )
 ) ;techLayerProperties

 techDerivedLayers(
 ;( DerivedLayerName          #          composition  )
 ;( ----------------          ------     ------------ )
  ( noOverlapLayer1           10001           ( POLY1      'and    DIFF      ))
 ) ;techDerivedLayers

) ;layerDefinitions


;********************************
; LAYER RULES
;********************************
layerRules(

 equivalentLayers(
 ;( list of layers )
 ;( -------------- )
  ( ("WELLBODY" "drawing")	PSUB       )
 ) ;equivalentLayers

 functions(
 ;( layer                       function        [maskNumber])
 ;( -----                       --------        ------------)
  ( PWELL                    	"pwell"     	1            )
  ( NWELL                    	"nwell"     	2            )
  ( DIFF                     	"ndiff"     	3            )
  ( POLY1                    	"poly"      	4            )
  ( CONT                     	"cut"       	5            )
  ( METAL1                   	"metal"     	6            )
  ( VIA12                    	"cut"       	7            )
  ( METAL2                   	"metal"     	8            )
  ( VIA23                    	"cut"       	9            )
  ( METAL3                   	"metal"     	10           )
  ( VICO                     	"cut"       	11           )
  ( MICO                     	"metal"     	12           )
  ( VIAD                     	"cut"       	13           )
  ( MD                       	"metal"     	14           )
 ) ;functions

 mfgResolutions(
 ;( layer                       mfgResolution )
 ;( -----                       ------------- )
 ) ;mfgResolutions

 routingDirections(
 ;( layer                       direction     )
 ;( -----                       ---------     )
 ) ;routingDirections

 incompatibleLayers(
 ;( layer                       incompatibleLayers       )
 ;( -----                       ------------------       )
 ) ;incompatibleLayers

 labelLayers(
 ;( textLayer   layers        )
 ;( ---------   ----------------------------------        )
 ) ;labelLayers

 stampLabelLayers(
 ;( textLayer   layers        )
 ;( ---------   ----------------------------------        )
 ) ;stampLabelLayers

 currentDensity(
 ;( rule                	layer1    	layer2    	value    )
 ;( ----                	------    	------    	-----    )
 ) ;currentDensity

 currentDensityTables(
 ;( rule                	layer1    
 ;  (( index1Definitions	[index2Definitions]) [defaultValue] )
 ;  (table))
 ;( ----------------------------------------------------------------------)
 ) ;currentDensityTables

) ;layerRules


;********************************
; VIADEFS
;********************************
viaDefs(

 standardViaDefs(
 ;( viaDefName	layer1	layer2	(cutLayer cutWidth cutHeight [resistancePerCut]) 
 ;   (cutRows	cutCol	(cutSpace)) 
 ;   (layer1Enc) (layer2Enc)	(layer1Offset)	(layer2Offset)	(origOffset) 
 ;   [implant1	 (implant1Enc)	[implant2	(implant2Enc) [well/substrate]]]) 
 ;( -------------------------------------------------------------------------- ) 
  ( MICO_M2     	METAL2      MICO        	("VICO" 0.36 0.36)
     (1 1 (0.35 0.35))
     (0.1 0.1)	(0.1 0.1)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( MD_M3       	METAL3      MD          	("VIAD" 0.36 0.36)
     (1 1 (0.35 0.35))
     (0.06 0.06)	(0.09 0.09)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M3_M2       	METAL2      METAL3      	("VIA23" 0.36 0.36)
     (1 1 (0.35 0.35))
     (0.06 0.06)	(0.09 0.09)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M2_M1       	METAL1      METAL2      	("VIA12" 0.26 0.26)
     (1 1 (0.26 0.26))
     (0.06 0.06)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M1_SUB      	DIFF        METAL1      	("CONT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     PIMP        	(0.02 0.02)
  )
  ( M1_PACTIVE  	DIFF        METAL1      	("CONT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     PIMP        	(0.18 0.18)
  )
  ( M1_NWELL    	DIFF        METAL1      	("CONT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     NIMP        	(0.02 0.02)	NWELL       	(0.16 0.16)
  )
  ( M1_NACTIVE  	DIFF        METAL1      	("CONT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     NIMP        	(0.18 0.18)
  )
  ( M1_PPOLY1   	POLY1       METAL1      	("CONT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     PIMP        	(0.18 0.18)
  )
  ( M1_NPOLY1   	POLY1       METAL1      	("CONT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     NIMP        	(0.18 0.18)
  )
  ( M1_DIFF     	DIFF        METAL1      	("CONT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( M1_POLY1    	POLY1       METAL1      	("CONT" 0.22 0.22)
     (1 1 (0.25 0.25))
     (0.1 0.1)	(0.06 0.06)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
 ) ;standardViaDefs

 customViaDefs(
 ;( viaDefName libName cellName viewName layer1 layer2 resistancePerCut)
 ;( ---------- ------- -------- -------- ------ ------ ----------------)
 ) ;customViaDefs

 standardViaVariants(
 ;( viaVariantName viaDefName (cutLayer cutWidth cutHeight) 
 ;   (cutRows	cutCol	(cutSpace)) 
 ;   (layer1Enc) (layer2Enc)	(layer1Offset)	(layer2Offset)	(origOffset) 
 ;   (implant1Enc) (implant2Enc) (cut_pattern) ) 
 ;( -------------------------------------------------------------------------- ) 
 ) ;standardViaVariants

 customViaVariants(
 ;(viaVariantName viaDefName (paramName paramValue) ...)
 ;( -------------------------------------------------------------------------- )
 ) ;customViaVariants

) ;viaDefs



;********************************
; CONSTRAINT GROUPS
;********************************
constraintGroups(

 ;( group	[override] )
 ;( -----	---------- )
  ( "default"	nil
  ) ;default

 ;( group	[override] )
 ;( -----	---------- )
  ( "virtuosoDefaultExtractorSetup"	nil

    interconnect(
     ( validLayers   (BPLY  EPLY  CTM2  MICO  VICO  MD  VIAD  METAL3  VIA23  METAL2  VIA12  METAL1  CONT  POLY2  POLY1  OD2  DIFF  NWELL  ) )
     ( errorLayer    noOverlapLayer1 )
    ) ;interconnect
  ) ;virtuosoDefaultExtractorSetup

 ;( group	[override] )
 ;( -----	---------- )
  ( "foundry"	nil

    spacings(
     ( minWidth                   "NWELL"	0.86 )
     ( minSpacing                 "NWELL"	1.4 )
     ( minSameNetSpacing          "NWELL"	1.4 )
     ( minWidth                   "NTN"	0.74 )
     ( minSpacing                 "NTN"	0.86 )
     ( minWidth                   "DIFF"	0.22 )
     ( minSpacing                 "DIFF"	0.28 )
     ( minSameNetSpacing          "DIFF"	0.28 )
     ( minArea                    "DIFF"	0.202 )
     ( minSpacing                 "OD2"	0.45 )
     ( minWidth                   "POLY1"	0.18 )
     ( minSpacing                 "POLY1"	0.25 )
     ( minSameNetSpacing          "POLY1"	0.25 )
     ( minWidth                   "NIMP"	0.44 )
     ( minSpacing                 "NIMP"	0.44 )
     ( minArea                    "NIMP"	0.3844 )
     ( minWidth                   "PIMP"	0.44 )
     ( minSpacing                 "PIMP"	0.44 )
     ( minArea                    "PIMP"	0.3844 )
     ( minWidth                   "RPO"	0.43 )
     ( minSpacing                 "RPO"	0.43 )
     ( minArea                    "RPO"	2.0 )
     ( minWidth                   "CONT"	0.22 )
     ( minSpacing                 "CONT"	0.25 )
     ( minWidth                   "METAL1"	0.23 )
     ( minSpacing                 "METAL1"	0.23 )
     ( minArea                    "METAL1"	0.202 )
     ( minWidth                   "VIA12"	0.26 )
     ( minSpacing                 "VIA12"	0.26 )
     ( minWidth                   "METAL2"	0.28 )
     ( minSpacing                 "METAL2"	0.28 )
     ( minArea                    "METAL2"	0.202 )
     ( minWidth                   "VIA23"	0.36 )
     ( minSpacing                 "VIA23"	0.35 )
     ( minWidth                   "METAL3"	0.44 )
     ( minSpacing                 "METAL3"	0.46 )
     ( minArea                    "METAL3"	0.562 )
     ( minWidth                   "VIAD"	0.36 )
     ( minSpacing                 "VIAD"	0.35 )
     ( minWidth                   "MD"	0.44 )
     ( minSpacing                 "MD"	0.46 )
     ( minArea                    "MD"	0.562 )
     ( minWidth                   "VICO"	0.36 )
     ( minSpacing                 "VICO"	0.35 )
     ( minWidth                   "MICO"	0.5 )
     ( minSpacing                 "MICO"	0.2 )
     ( minArea                    "MICO"	0.562 )
     ( minWidth                   "VTM_N"	0.74 )
     ( minSpacing                 "VTM_N"	0.44 )
     ( minWidth                   "VTM_P"	0.74 )
     ( minSpacing                 "VTM_P"	0.44 )
     ( minWidth                   "HRI"	0.44 )
     ( minSpacing                 "HRI"	0.44 )
     ( minArea                    "HRI"	0.3844 )
     ( minWidth                   "CTM2"	0.4 )
     ( minSpacing                 "CTM2"	0.8 )
     ( minSpacing                 "NTN"	"DIFF"		0.52 )
     ( minSpacing                 "NTN"	"NWELL"		1.66 )
     ( minSpacing                 "NWELL"	"DIFF"		0.43 )
     ( minSpacing                 "OD2"	"DIFF"		0.32 )
     ( minSpacing                 "POLY1"	"DIFF"		0.1 )
     ( minSpacing                 "NIMP"	"DIFF"		0.26 )
     ( minSpacing                 "PIMP"	"DIFF"		0.26 )
     ( minSpacing                 "RPO"	"DIFF"		0.22 )
     ( minSpacing                 "RPO"	"CONT"		0.22 )
     ( minSpacing                 "RPO"	"POLY1"		0.3 )
     ( minSpacing                 "CONT"	"POLY1"		0.16 )
     ( minSpacing                 "CONT"	"DIFF"		0.2 )
     ( minSpacing                 "VTM_N"	"DIFF"		0.7 )
     ( minSpacing                 "VTM_N"	"NWELL"		0.43 )
     ( minSpacing                 "VTM_P"	"DIFF"		0.7 )
     ( minSpacing                 "HRI"	"NIMP"		0.26 )
     ( minSpacing                 "HRI"	"PIMP"		0.26 )
    ) ;spacings

    orderedSpacings(
     ( minEnclosure               "NTN"	"DIFF"		0.26 )
     ( minEnclosure               "NWELL"	"DIFF"		0.43 )
     ( minEnclosure               "OD2"	"DIFF"		0.32 )
     ( minEnclosure               "DIFF"	"POLY1"		0.32 )
     ( minEnclosure               "POLY1"	"DIFF"		0.22 )
     ( minEnclosure               "NIMP"	"DIFF"		0.18 )
     ( minEnclosure               "PIMP"	"DIFF"		0.18 )
     ( minEnclosure               "RPO"	"DIFF"		0.22 )
     ( minEnclosure               "DIFF"	"RPO"		0.22 )
     ( minEnclosure               "RPO"	"POLY1"		0.22 )
     ( minEnclosure               "DIFF"	"CONT"		0.1 )
     ( minEnclosure               "POLY1"	"CONT"		0.1 )
     ( minEnclosure               "PIMP"	"CONT"		0.12 )
     ( minEnclosure               "NIMP"	"CONT"		0.12 )
     ( minEnclosure               "METAL1"	"CONT"		0.005 )
     ( minEnclosure               "METAL1"	"VIA12"		0.01 )
     ( minEnclosure               "METAL2"	"VIA12"		0.01 )
     ( minEnclosure               "METAL2"	"VIA23"		0.01 )
     ( minEnclosure               "METAL3"	"VIA23"		0.09 )
     ( minEnclosure               "METAL3"	"VIAD"		0.01 )
     ( minEnclosure               "MD"	"VIAD"		0.09 )
     ( minEnclosure               "METAL2"	"VICO"		0.1 )
     ( minEnclosure               "MICO"	"VICO"		0.1 )
     ( minEnclosure               "VTM_N"	"DIFF"		0.26 )
     ( minEnclosure               "VTM_P"	"DIFF"		0.26 )
     ( minEnclosure               "HRI"	"POLY1"		0.26 )
     ( minEnclosure               "CTM2"	"VIA23"		0.24 )
     ( minEnclosure               "METAL2"	"CTM2"		0.4 )
    ) ;orderedSpacings

    spacings(
     ( minWidth                   "NDIFF"	0.0 )
     ( minSpacing                 "NDIFF"	0.0 )
     ( minWidth                   "PDIFF"	0.0 )
     ( minSpacing                 "PDIFF"	0.0 )
    ) ;spacings

    orderedSpacings(
     ( minEnclosure               "NDIFF"	"CONT"		0.1 )
     ( minEnclosure               "PDIFF"	"CONT"		0.1 )
     ( minEnclosure               "NWELL"	"PDIFF"		0.0 )
     ( minEnclosure               "NWELL"	"NDIFF"		0.0 )
    ) ;orderedSpacings

    spacings(
     ( minSpacing                 "NWELL"	"NDIFF"		0.0 )
    ) ;spacings

    orderedSpacings(
     ( minEnclosure               "PIMP"	"PDIFF"		0.18 )
    ) ;orderedSpacings

    spacings(
     ( minSpacing                 "PIMP"	"NDIFF"		0.26 )
     ( minSpacing                 "PIMP"	"PDIFF"		0.26 )
    ) ;spacings

    orderedSpacings(
     ( minEnclosure               "NIMP"	"NDIFF"		0.18 )
    ) ;orderedSpacings

    spacings(
     ( minSpacing                 "NIMP"	"NDIFF"		0.26 )
     ( minSpacing                 "NIMP"	"PDIFF"		0.26 )
     ( minSpacing                 "NIMP"	"PIMP"		0.0 )
    ) ;spacings

    orderedSpacings(
     ( minEnclosure               "PDIFF"	"POLY1"		0.0 )
     ( minEnclosure               "NDIFF"	"POLY1"		0.0 )
    ) ;orderedSpacings

    spacings(
     ( minSpacing                 "POLY1"	"PDIFF"		0.1 )
    ) ;spacings

    spacings(
    ;( constraint		layer1		[layer2]	value  )
    ;( ----------		------		--------	-----  )
     ( minExtension               "POLY1" 	0.0 )
    ) ;spacings

    electrical(
    ;( constraint		layer1		[layer2]	value  )
    ;( ----------		------		--------	-----  )
     ( contactRes                 "NIMP" 	0.5324 )
     ( contactRes                 "PIMP" 	0.484 )
     ( contactRes                 "POLY1" 	0.37752 )
    ) ;electrical
  ) ;foundry
) ;constraintGroups


;********************************
; DEVICES
;********************************
devices(
tcCreateCDSDeviceClass()

;
; no cdsVia devices
;

;
; no cdsMos devices
;

;
; no cdsResistor devices
;
;
; no ruleContact devices
;


multipartPathTemplates(
; ( name [masterPath] [offsetSubpaths] [encSubPaths] [subRects] )
; 
;   masterPath:
;   (layer [width] [choppable] [endType] [beginExt] [endExt] [justify] [offset]
;   [connectivity])
; 
;   offsetSubpaths:
;   (layer [width] [choppable] [separation] [justification] [begOffset] [endOffset]
;   [connectivity])
; 
;   encSubPaths:
;   (layer [enclosure] [choppable] [separation] [begOffset] [endOffset]
;   [connectivity])
; 
;   subRects:
;   (layer [width] [length] [choppable] [separation] [justification] [space] [begOffset] [endOffset] [gap] 
;   [connectivity] [beginSegOffset] [endSegOffset])
; 
;   connectivity:
;   ([I/O type] [pin] [accDir] [dispPinName] [height] [ layer]
;    [layer] [justification] [font] [textOptions] [orientation]
;    [refHandle] [offset])
; 
; ( --------------------------------------------------------------------- )
)  ;multipartPathTemplates


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Opus Symbolic Device Class Definition
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;
; no other device classes
;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Opus Symbolic Device Declaration
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Device Extraction Declaration
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


) ;devices


;********************************
; LE RULES
;********************************
leRules(

 leLswLayers(
 ;( layer               purpose         )
 ;( -----               -------         )
 ) ;leLswLayers

) ;leRules


;********************************
; SITEDEFS
;********************************
siteDefs(

 scalarSiteDefs(
 ;( siteDefName          type width  height  symInX symInY symInR90)
 ;( -----------          ---- -----  ------  ------ ------ -------)
 ) ;scalarSiteDefs

 arraySiteDefs(
 ; ( name	type
 ;  ((siteDefName     dx      dy      orientation) ...)
 ;   [symX] [symY] [symR90] )

 ) ;arraySiteDefs

) ;siteDefs


;********************************
; VIASPECS
;********************************

viaSpecs(
 ;(layer1  layer2  (viaDefName ...) 
 ;   [(        
 ;	(layer1MinWidth layer1MaxWidth layer2MinWidth layer2MaxWidth 
 ;            (viaDefName ...)) 
 ;	...         
 ;   )])       
 ;( ------------------------------------------------------------------------ ) 
) ;viaSpecs
