;----------------------------------------------------------------------------
; @(#)$CDS: virtuoso version 6.1.4 03/26/2010 00:22 (sjfnl009) $
;----------------------------------------------------------------------------

;----------------------------------------------------------------------------
; QRC 8.1 Template Version 1
;----------------------------------------------------------------------------

vuiRcxSetupFormOptions = '(
    ((?vuiRCXFlowTab)
        (vuiOutputFormatSpiceButton      t)
        (subNode      nil)
        (extractMosAp      t)
        (callProcReadOnly      nil)
        (extractMosDiff      "3")
        (substrateProfile      "NONE")
        (vuiOutputFormatSpectreButton      t)
        (vuiOutputFormatExtractedViewButton      t)
        (parasiticResComp      "presistor")
        (ind1PropIdentifier      "ind1")
        (vuiOutputFormatTransistorDspfButton      t)
        (ind2PropIdentifier      "ind2")
        (indPropIdentifierReadOnly      nil)
        (extractMosDiffReadOnly      nil)
        (vuiOutputFormatTransistorSpefButton      t)
        (ind2PropIdentifierReadOnly      nil)
        (libPrefix      "")
        (parasiticIndCompReadOnly      nil)
        (extractMosApReadOnly      nil)
        (extractMosRes      nil)
        (extractMosResReadOnly      nil)
        (parasiticCapComp      "pcapacitor")
        (resPropIdentifierReadOnly      nil)
        (parasiticCapCompReadOnly      nil)
        (p2lvsSetBool      nil)
        (substrateProfileReadOnly      nil)
        (mindPropIdentifier      "k")
        (vuiOutputFormatLvsExtractedViewButton      t)
        (vuiOutputFormatSpefButton      t)
        (parasiticMIndComp      "pmind")
        (resPropIdentifier      "r")
        (capPropIdentifier      "c")
        (vuiOutputFormatDspfButton      t)
        (parasiticMIndCompReadOnly      nil)
        (ind1PropIdentifierReadOnly      nil)
        (callProc      "")
        (capPropIdentifierReadOnly      nil)
        (parasiticIndComp      "pinductor")
        (vuiRCXDefaultOutputFormatType      "Spectre")
        (parasiticResCompReadOnly      nil)
        (indPropIdentifier      "l")
        (checkCellView      nil)
        (mindPropIdentifierReadOnly      nil)
    )
    ((?vuiRCXExtractionTab)
        (vuiRCXRLCK      t)
        (vuiRCXEnableRCXFS      t)
        (ladderNetwork      nil)
        (splitPinDistance      "5")
        (Maxfracturelength      "infinite")
        (vuiRCXSNP      t)
        (refNode      "gnd!")
        (rcxfsHigh      t)
        (vuiRCXFSFCAN      t)
        (vuiRcxFSExtractionCheckLimit      "Full Chip All Nets")
        (vuiRCXCOnly      t)
        (vuiRCXROnly      t)
        (vuiRCXSP      t)
        (vuiRCXEHrcx      nil)
        (vuiRCXFCAN      t)
        (splitPins      nil)
        (vuiRCXFSSP      t)
        (vuiRCXFSSN      t)
        (temperature      "25.0")
        (netNameSpace      "Layout Names")
        (globalFrequency      "0")
        (excludeViaCap      nil)
        (fractureLengthUnits      "microns")
        (multFactor      "1.0")
        (vuiRCXRLC      t)
        (vuiRCXFSEN      t)
        (peecMode      nil)
        (vuiRcxExtractionCheckLimit      "Full Chip All Nets")
        (vuiRCXExtractDefault      "RC")
        (vuiRCXFCSN      t)
        (vuiRCXEN      t)
        (vuiRCXRCOnly      t)
    )
    ((?vuiRCXFilteringTab)
        (vuiRCXexcludeFloatLimit      "2000000")
        (vuiRCXmFactor      "infinite")
        (vuiRCXminCByPerc      "0.1")
        (vuiRCXArrayViasSpacingReadOnly      nil)
        (vuiRCXexcludeSelfCaps      nil)
        (vuiRCXexcludeFloatingNets      nil)
        (vuiRCXexcludeFloatLimitReadOnly      nil)
        (vuiRCXDanglingR      nil)
        (vuiRCXArrayViasSpacing      "auto")
        (vuiRCXFilterSizeReadOnly      nil)
        (vuiRCXmFactorW      nil)
        (vuiRCXFilterSize      "2.0")
        (vuiRCXexcludeFloatingNetsReadOnly      nil)
        (vuiRCXreduceRC      nil)
        (vuiRCXexcludeSelfCapsReadOnly      nil)
        (vuiRCXmFactorWReadOnly      nil)
        (vuiRCXmergeParallelR      nil)
        (vuiRCXminRReadOnly      nil)
        (vuiRCXreduceRCReadOnly      nil)
        (vuiRCXMaxMergedViaSize      "auto")
        (vuiRCXmergeParallelRReadOnly      nil)
        (vuiRCXminC      "0.01")
        (vuiRCXmFactorReadOnly      nil)
        (vuiRCXminR      "0.001")
        (vuiRCXminCReadOnly      nil)
        (vuiRCXDanglingRReadOnly      nil)
        (vuiRCXMaxMergedViaSizeReadOnly      nil)
    )
    ((?vuiRCXNetlistingTab)
        (vuiRCXCouplingValues      "Double")
        (vuiRCXSubNodeChar      "#")
        (vuiRCXImportGlobals      nil)
        (vuiRCXAddExplicitVias      nil)
        (vuiRCXIgnoreNets      "")
        (vuiRCXInstanceOff      nil)
        (vuiRCXViaEffectOff      nil)
        (vuiRCXXy_D      nil)
        (vuiRCXXy_r      nil)
        (vuiRCXXy_R      nil)
        (vuiRCXIgnoreLayer      "")
        (vuiRCXHierarchyDelimiter      "/")
        (vuiRCXXy_M      nil)
        (vuiRCXResModels      "Include As Comment")
        (vuiRCXXy_c      nil)
        (vuiRCXstampingOff      nil)
        (vuiRCXOutputNetNameSpace      "Schematic")
        (vuiRCXParasiticResWidth      "Off")
        (vuiRCXVirtualMetalFill      "Fine Shape")
        (vuiRCXXy_Q      nil)
        (vuiRCXDeviceFingerDelimiter      "@")
        (vuiRCXBusBit      "[]")
        (vuiRCXSaveFillShapes      nil)
        (vuiRCXCapModels      "Include As Comment")
        (vuiRCXParasiticResModels      "Include As Comment")
        (vuiRCXParasiticCapModels      "Include As Comment")
        (vuiRCXXy_C      nil)
        (vuiRCXParasiticResLength      nil)
    )
    ((?vuiRCXRunDetailsTab)
        (vuiRCXLSFButton      nil)
        (vuiRcxMp      nil)
        (vuiRcxRunMode      "Multi Processing")
        (vuiRcxNumOfP      "1")
        (machineLoc      "local")
        (vuiRCXMultiMachineButton      nil)
        (vuiRcxTempDir      "/tmp")
    )

)
